Update custom-layouts.md
nuejs/nue pull request #288
Opened 2024-08-05 18:23 UTC by seneca

First read of www2 docs with proposed changes.

2024-08-05 22:29 UTC, nobkd requested changes

2024-08-05 22:29 UTC, nobkd commented on packages/nuejs.org/docs/custom-layouts.md
> +The layouts are written in an HTML-based [template language](template-syntax.html) and the template variables have access to the [project data](project-structure.html#data).
```suggestion
The layouts are written in a HTML-based [template language](template-syntax.html) and the template variables have access to the [project data](project-structure.html#data).
```

2024-08-05 22:58 UTC, seneca commented
I agree. Should be a not an.

2024-08-06 00:54 UTC, nobkd approved these changes

2024-08-06 13:08 UTC, tipiirai approved these changes

2024-08-06 13:08 UTC, merged

2024-08-06 13:08 UTC, tipiirai commented
Thank you!