Update global-design-system.md
nuejs/nue pull request #289
Opened 2024-08-05 18:58 UTC by seneca

Please review these changes just in case.

2024-08-05 22:32 UTC, nobkd requested changes

2024-08-05 22:32 UTC, nobkd commented on packages/nuejs.org/docs/global-design-system.md
> +This content assembly format consistently generates identical HTML output, making it a perfect fit for the global design system. The resulting markup is 100% headless, allowing you to transform the a
```suggestion
This content assembly format consistently generates identical HTML output, making it a perfect fit for the global design system. The resulting markup is 100% headless, allowing you to transform the appearance of your content with only CSS.
```

2024-08-05 23:03 UTC, seneca commented
On re-reading this sentence I tend to agree with you here.

2024-08-06 00:55 UTC, nobkd approved these changes

2024-08-06 13:10 UTC, tipiirai commented
Damn. This has been changed by us both and now has conflicts. Can you resolve? 🙏

2024-08-06 14:27 UTC, nobkd commented
Please check, if I merged something incorrectly. Thanks

2024-08-13 08:18 UTC, merged

2024-08-13 08:19 UTC, tipiirai commented
Awesome. Thanks for fixing the conflicts!